name: 📚 Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: '[Docs]: '
labels: ['documentation', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear instructions
        - Broken links
        - Typos or grammar errors
        - Accessibility issues
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: e.g., README.md, API docs, getting started guide, etc.

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail
      placeholder: What's wrong with the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: What changes would make this better?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here
